/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicassign9;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Prerna Dutta
 */
public class ClipLine extends javax.swing.JFrame {

    /**
     * Creates new form DrawLine
     */
    JFrame fram=new JFrame();
    float px;
    float py;
    float qx;
    float qy;
    Point min=new Point();
    Point max=new Point();
    int flag=0;
    public ClipLine() {
        initComponents();
         this.getContentPane().setBackground(new java.awt.Color(168,51,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Px = new javax.swing.JTextField();
        Py = new javax.swing.JTextField();
        Qx = new javax.swing.JTextField();
        Qy = new javax.swing.JTextField();
        Minx = new javax.swing.JTextField();
        Miny = new javax.swing.JTextField();
        Maxx = new javax.swing.JTextField();
        Maxy = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cohen SutherLand Algorithm");

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        jButton1.setText("Draw and Clip");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Px.setText("P->x");

        Py.setText("P->y");

        Qx.setText("Q->x");

        Qy.setText("Q->y");

        Minx.setText("Min->x");

        Miny.setText("Min->y");

        Maxx.setText("Max->x");
        Maxx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxxActionPerformed(evt);
            }
        });

        Maxy.setText("Max->y");

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Px)
                    .addComponent(Py)
                    .addComponent(Qx)
                    .addComponent(Qy)
                    .addComponent(Minx)
                    .addComponent(Miny)
                    .addComponent(Maxx)
                    .addComponent(Maxy)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(Px, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Py, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Qx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Qy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Minx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Miny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Maxx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Maxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int draw=0;
       if(flag!=1){
           flag=1;
       try{
       px=(float)Integer.parseInt(Px.getText());
       py=(float)Integer.parseInt(Py.getText());
       qx=(float)Integer.parseInt(Qx.getText());
       qy=(float)Integer.parseInt(Qy.getText());
       float minx=(float)Integer.parseInt(Minx.getText());
       float miny=(float)Integer.parseInt(Miny.getText());
       float maxx=(float)Integer.parseInt(Maxx.getText());
       float maxy=(float)Integer.parseInt(Maxy.getText());
       Graphics2D gfx=(Graphics2D)Panel.getGraphics();
       Point p=new Point(px,py);
       Point q=new Point(qx,qy);
       min=new Point(minx,miny);
       max=new Point(maxx,maxy);
       p.assignbitcode(min,max);
       q.assignbitcode(min, max);
       float m=(qy-py)/(qx-px);
       System.out.println(" m "+m);
       float c=m*(-px)+py;
       gfx.setColor(Color.red);
       Polygon poly=new Polygon();
       poly.addPoint((int)min.x, (int)min.y);
       poly.addPoint((int)max.x, (int)min.y);
       poly.addPoint((int)max.x,(int)max.y);
       poly.addPoint((int)min.x,(int)max.y);
       gfx.drawPolygon(poly);
       gfx.setColor(Color.BLACK);
       gfx.drawLine((int)px, (int)py, (int)qx, (int)qy);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
           System.out.println("Thread error");
        }
        gfx.setColor(Color.WHITE);
        gfx.drawLine((int)px, (int)py, (int)qx, (int)qy);
        gfx.setColor(Color.BLACK);
       do{
           if(Point.TrivialAcceptance(p, q)){
               draw=1;
               break;
           }
           if(Point.TrivialRejection(p, q)){
               break;
           }
           if(!p.checkZero()){
               for(int i=0;i<4;i++){
                   if(p.bitcode[i]==1){
                       System.out.println(" m "+m);
                     p.clip(m, c, i+1, min, max);
                     break;
                   }
               }
           }
           else if(!q.checkZero()){
               for(int i=0;i<4;i++){
                   if(q.bitcode[i]==1){
                     q.clip(m, c, i+1, min, max);
                     break;
                   }
               }
           }
       }while(true);
       if(draw==1){
           gfx.drawLine((int)p.x,(int)p.y,(int)q.x,(int)q.y);
       }
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(fram,"Please Enter All the fields.");
       }
       }
       else
           JOptionPane.showMessageDialog(fram,"Clear Screen First.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MaxxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaxxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(flag==1){
        Graphics2D gfx=(Graphics2D)Panel.getGraphics();
        gfx.setColor(Color.WHITE);
        Polygon poly=new Polygon();
        poly.addPoint((int)min.x, (int)min.y);
        poly.addPoint((int)max.x, (int)min.y);
        poly.addPoint((int)max.x,(int)max.y);
        poly.addPoint((int)min.x,(int)max.y);
        gfx.drawPolygon(poly);
        gfx.drawLine((int)px, (int)py, (int)qx, (int)qy);
        flag=0;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClipLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClipLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClipLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClipLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClipLine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Maxx;
    private javax.swing.JTextField Maxy;
    private javax.swing.JTextField Minx;
    private javax.swing.JTextField Miny;
    private javax.swing.JPanel Panel;
    private javax.swing.JTextField Px;
    private javax.swing.JTextField Py;
    private javax.swing.JTextField Qx;
    private javax.swing.JTextField Qy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
